// <auto-generated />
namespace MesjidCommittee.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class changedphonenumbertodouble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedphonenumbertodouble));
        
        string IMigrationMetadata.Id
        {
            get { return "201509050341323_changed phone number to double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
