// <auto-generated />
namespace MesjidCommittee.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedreturnurltouseraccounts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedreturnurltouseraccounts));
        
        string IMigrationMetadata.Id
        {
            get { return "201603200323590_added returnurl to user accounts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
