// <auto-generated />
namespace MesjidCommittee.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class madeDOBoptionalandupdatedcitywithcapitalfirstletter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madeDOBoptionalandupdatedcitywithcapitalfirstletter));
        
        string IMigrationMetadata.Id
        {
            get { return "201506231659316_made DOB optional and updated city with capital first letter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
