// <auto-generated />
namespace MesjidCommittee.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class childTableNowHasActivities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(childTableNowHasActivities));
        
        string IMigrationMetadata.Id
        {
            get { return "201508080550040_childTableNowHasActivities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
