// <auto-generated />
namespace MesjidCommittee.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedrequiredtophoneandemail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedrequiredtophoneandemail));
        
        string IMigrationMetadata.Id
        {
            get { return "201506300336397_added required to phone and email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
